-- lua/keymaps/mappings.lua

-- Helper function for setting key mappings
-- 'n' stands for normal mode
-- 'lhs' is the left-hand side of the keymap (the keys you press)
-- 'rhs' is the right-hand side (the command that is executed)
-- 'desc' provides a description for the mapping (useful for documentation plugins)
local map = vim.api.nvim_set_keymap
local opts = { noremap = true, silent = true }

local function nmap(lhs, rhs, desc)
  map('n', lhs, rhs, vim.tbl_extend('force', opts, { desc = desc }))
end

-- Telescope Mappings
nmap('<leader>ff', '<cmd>Telescope find_files<cr>', 'Find Files')         -- Find files using Telescope
nmap('<leader>te', '<cmd>Telescope<cr>', 'Open Telescope')               -- Open Telescope's main menu
nmap('<leader>fg', '<cmd>Telescope live_grep<cr>', 'Live Grep')          -- Search text in project using live grep

-- NvimTree Mappings with nv- prefix
nmap('<leader>nvf', '<cmd>NvimTreeFindFile<cr>', 'Find Current File')    -- Highlight current file in NvimTree
nmap('<leader>nvo', '<cmd>NvimTreeToggle<cr>', 'Toggle NvimTree')        -- Open or close NvimTree
nmap('<leader>nvr', '<cmd>NvimTreeRefresh<cr>', 'Refresh NvimTree')      -- Refresh the file explorer
nmap('<leader>nvc', '<cmd>NvimTreeCollapse<cr>', 'Collapse All Folders') -- Collapse all folders in NvimTree
nmap('<leader>nva', '<cmd>NvimTreeFocus<cr>', 'Focus on NvimTree')       -- Focus on the NvimTree window
nmap('<leader>nvn', '<cmd>NvimTreeOpen<cr>', 'Open File/Directory')      -- Open a file or directory under the cursor

-- Markdown Preview
nmap('<leader>mp', '<cmd>MarkdownPreview<cr>', 'Markdown Preview')       -- Start markdown preview in browser

-- VimWiki Mappings
nmap('<leader>ww', '<cmd>VimWikiIndex<cr>', 'Open VimWiki Index')        -- Open VimWiki index page

-- VimTex Mappings for LaTeX
nmap('<leader>lbc', '<cmd>VimtexCompile<cr>', 'Compile LaTeX Document')  -- Compile the current LaTeX document
nmap('<leader>lv', '<cmd>VimtexView<cr>', 'View LaTeX PDF')              -- View the compiled PDF in a viewer
nmap('<leader>lec', '<cmd>VimtexStop<cr>', 'Stop LaTeX Compilation')     -- Stop the ongoing LaTeX compilation
nmap('<leader>lcc', '<cmd>VimtexClean<cr>', 'Clean Auxiliary Files')     -- Clean auxiliary files generated by LaTeX
